DATASET_PATH = "./dataset2019/archive/training/"
DATASET_LABELS_PATH = "./Dataset/labels"
DATASET_IMAGES_FLAIR_PATH = "./Dataset/images_flair"
DATASET_IMAGES_T1CE_PATH = "./Dataset/images_t1ce"
DATASET_IMAGES_T1_PATH = "./Dataset/images_t1"
DATASET_IMAGES_T2_PATH = "./Dataset/images_t2"
IMAGES_TRAIN_PATH = './Folders/images/train'
IMAGES_VALIDATION_PATH = './Folders/images/validation'
IMAGES_TEST_PATH = './Folders/images/test'
LABELS_TRARIN_PATH = './Folders/labels/train'
LABELS_VALIDATION_PATH = './Folders/labels/validation'
LABELS_TEST_PATH = './Folders/labels/test'
HISTORY_PATH = './History'
LOG_PATH = './History/Log/'
OUTPUT_PATH = './History/Result/'
LOAD_BEST_DICE_PATH = './History/Checkpoint/Best_Dice.pth.gz'
LOG_FILE = 'train_log.txt'
OUTPUT_FILE = 'output.txt'
DATASET_HIST_IMAGES_TRAIN_PATH = './Folders_hist/images/train'
DATASET_HIST_IMAGES_VALIDATION_PATH = './Folders_hist/images/validation'
DATASET_HIST_IMAGES_TEST_PATH = './Folders_hist/images/test'
DATASET_HIST_LABELS_TRARIN_PATH = './Folders_hist/labels/train'
DATASET_HIST_LABELS_VALIDATION_PATH = './Folders_hist/labels/validation'
DATASET_HIST_LABELS_TEST_PATH = './Folders_hist/labels/test'

TEST_IMAGE = './Folders/images/test/image12.nii'
TEST_LABEL = './Folders/labels/test/label12.nii'
RESULT_PATH = './Result/result_5.nii'
RESULT_FILE_PATH_NAME = './Result/result_'
WEIGHTS_PATH = './History/Checkpoint/Best_Dice.pth.gz'
RESULT_DICE_FILE = 'result_dice.txt'

WEIGHTS_FLAG = False
RESAMPLE_FLAG = True
LEARNING_RATE = 0.1
MOMENTUM = 0.9
WEIGHT_DECAY = 3e-5
#NESTEROV = True
INCREASE_FACTOR_DATA = 3
NEW_RESOLUTION = (0.6, 0.6, 2.5)
PATCH_SIZE = [64, 32, 32]
DROP_RATIO = 0 
MIN_PIXEL = 0.1
BATCH_SIZE = 16
EPOCH_INIT = 1
EPOCH_COUNT = 30
EPOCH_N = EPOCH_INIT + EPOCH_COUNT
STRIDE_INPLANE = 64
STRIDE_LAYER = 16
LOAD_WEIGHTS_PATH = "./History/Checkpoint/Network_{}.pth.gz".format(EPOCH_INIT - 1)

TEST_RESAMPLE_FLAG = False
TEST_NEW_RESOLUTION = (1, 1, 2)
TEST_PATCH_SIZE = [64, 64, 32]
TEST_BATCH_SIZE = 1
SEGMENTATION_FLAG = True
PATCH_SIZE_FOR_CHECK = [256, 256, 256]
BATCH_SIZE_FOR_CHECK = 1
WRITE_IMAGE_FLAG = True

HIST_FLAG = False
if HIST_FLAG is True:
    IMAGES_TRAIN_PATH = DATASET_HIST_IMAGES_TRAIN_PATH
    IMAGES_VALIDATION_PATH = DATASET_HIST_IMAGES_VALIDATION_PATH
    IMAGES_TEST_PATH = DATASET_HIST_IMAGES_TEST_PATH
    LABELS_TRARIN_PATH = DATASET_HIST_LABELS_TRARIN_PATH
    LABELS_VALIDATION_PATH = DATASET_HIST_LABELS_VALIDATION_PATH
    LABELS_TEST_PATH = DATASET_HIST_LABELS_TEST_PATH
    TEST_IMAGE = './Folders_hist/images/test/image2.nii'
    TEST_LABEL = './Folders_hist/labels/test/label2.nii'
